"""initial CU-OS schema

Revision ID: 363702eea821
Revises: 
Create Date: 2026-08-28 15:26:18.791684
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = '363702eea821'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('block_address', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=120), nullable=True),
    sa.Column('precinct', sa.String(length=120), nullable=True),
    sa.Column('asset_type', sa.String(length=32), nullable=True),
    sa.Column('venue_owner', sa.String(length=200), nullable=True),
    sa.Column('partner_operator', sa.String(length=200), nullable=True),
    sa.Column('cu_coordinator', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('planned_launch_date', sa.Date(), nullable=True),
    sa.Column('actual_launch_date', sa.Date(), nullable=True),
    sa.Column('target_crew_size', sa.Integer(), nullable=False),
    sa.Column('place_confirmed', sa.Boolean(), nullable=False),
    sa.Column('partner_confirmed', sa.Boolean(), nullable=False),
    sa.Column('power_confirmed', sa.Boolean(), nullable=False),
    sa.Column('water_confirmed', sa.Boolean(), nullable=False),
    sa.Column('storage_confirmed', sa.Boolean(), nullable=False),
    sa.Column('equipment_allocated', sa.Boolean(), nullable=False),
    sa.Column('crew_sufficient', sa.Boolean(), nullable=False),
    sa.Column('leader_coverage_sufficient', sa.Boolean(), nullable=False),
    sa.Column('safety_ready', sa.Boolean(), nullable=False),
    sa.Column('programme_plan_ready', sa.Boolean(), nullable=False),
    sa.Column('checkin_method_ready', sa.Boolean(), nullable=False),
    sa.Column('launch_approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('code', name=op.f('uq_assets_code'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('pathways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathways')),
    sa.UniqueConstraint('code', name=op.f('uq_pathways_code'))
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preferred_name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('age_band', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=32), nullable=False),
    sa.Column('home_zone', sa.String(length=120), nullable=True),
    sa.Column('home_precinct', sa.String(length=120), nullable=True),
    sa.Column('travel_willingness', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('registration_source', sa.String(length=32), nullable=False),
    sa.Column('assisted_registration', sa.Boolean(), nullable=False),
    sa.Column('assisted_by', sa.String(length=200), nullable=True),
    sa.Column('disciple_status', sa.String(length=32), nullable=True),
    sa.Column('target_next_level', sa.String(length=16), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['people.id'], name=op.f('fk_people_mentor_id_people'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people')),
    sa.UniqueConstraint('phone_e164', name=op.f('uq_people_phone_e164'))
    )
    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_users_email'))
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_availability_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability')),
    sa.UniqueConstraint('person_id', 'weekday', 'start_time', 'end_time', name=op.f('uq_availability_person_id'))
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index('ix_availability_weekday', ['weekday'], unique=False)

    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_consents_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('person_id', 'consent_type', name=op.f('uq_consents_person_id'))
    )
    op.create_table('inbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('from_wa_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('button_payload', sa.String(length=64), nullable=True),
    sa.Column('text_body', sa.Text(), nullable=True),
    sa.Column('provider_timestamp', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_inbound_messages_person_id_people'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound_messages')),
    sa.UniqueConstraint('provider_message_id', name=op.f('uq_inbound_messages_provider_message_id'))
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pathway_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('required_for_deployment', sa.Boolean(), nullable=False),
    sa.Column('grants_role', sa.String(length=64), nullable=True),
    sa.Column('display_title', sa.String(length=120), nullable=True),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('assessment_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pathway_id'], ['pathways.id'], name=op.f('fk_modules_pathway_id_pathways'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules')),
    sa.UniqueConstraint('pathway_id', 'code', name=op.f('uq_modules_pathway_id'))
    )
    op.create_table('person_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('interest', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_person_interests_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_interests')),
    sa.UniqueConstraint('person_id', 'interest', name=op.f('uq_person_interests_person_id'))
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_shifts_asset_id_assets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts')),
    sa.UniqueConstraint('asset_id', 'service_date', name=op.f('uq_shifts_asset_id'))
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index('ix_shifts_service_date', ['service_date'], unique=False)

    op.create_table('deployment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_deployment_assignments_person_id_people'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('fk_deployment_assignments_shift_id_shifts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_assignments')),
    sa.UniqueConstraint('shift_id', 'person_id', name=op.f('uq_deployment_assignments_shift_id'))
    )
    with op.batch_alter_table('deployment_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_deployment_assignments_person', ['person_id'], unique=False)

    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('external_evidence_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['staff_users.id'], name=op.f('fk_qualifications_approved_by_id_staff_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_qualifications_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_qualifications_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qualifications')),
    sa.UniqueConstraint('person_id', 'module_id', name=op.f('uq_qualifications_person_id'))
    )
    op.create_table('scheduled_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('assessment_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_scheduled_events_module_id_modules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trainer_id'], ['staff_users.id'], name=op.f('fk_scheduled_events_trainer_id_staff_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_events'))
    )
    with op.batch_alter_table('scheduled_events', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_events_kind_status', ['kind', 'status'], unique=False)
        batch_op.create_index('ix_scheduled_events_starts_at', ['starts_at'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.Column('marked_by_id', sa.Integer(), nullable=True),
    sa.Column('assessment_outcome', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['scheduled_events.id'], name=op.f('fk_enrollments_event_id_scheduled_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by_id'], ['staff_users.id'], name=op.f('fk_enrollments_marked_by_id_staff_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_enrollments_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('event_id', 'person_id', name=op.f('uq_enrollments_event_id'))
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollments_status', ['status'], unique=False)

    op.create_table('event_acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(length=32), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=False),
    sa.Column('inbound_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['scheduled_events.id'], name=op.f('fk_event_acknowledgments_event_id_scheduled_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inbound_message_id'], ['inbound_messages.id'], name=op.f('fk_event_acknowledgments_inbound_message_id_inbound_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_event_acknowledgments_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_acknowledgments')),
    sa.UniqueConstraint('event_id', 'person_id', name=op.f('uq_event_acknowledgments_event_id'))
    )
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('to_wa_id', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['scheduled_events.id'], name=op.f('fk_outbound_messages_event_id_scheduled_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_outbound_messages_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbound_messages')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbound_messages_dedupe_key'))
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index('ix_outbound_messages_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outbound_messages_status')

    op.drop_table('outbound_messages')
    op.drop_table('event_acknowledgments')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollments_status')

    op.drop_table('enrollments')
    with op.batch_alter_table('scheduled_events', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_events_starts_at')
        batch_op.drop_index('ix_scheduled_events_kind_status')

    op.drop_table('scheduled_events')
    op.drop_table('qualifications')
    with op.batch_alter_table('deployment_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_deployment_assignments_person')

    op.drop_table('deployment_assignments')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index('ix_shifts_service_date')

    op.drop_table('shifts')
    op.drop_table('person_interests')
    op.drop_table('modules')
    op.drop_table('inbound_messages')
    op.drop_table('consents')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index('ix_availability_weekday')

    op.drop_table('availability')
    op.drop_table('staff_users')
    op.drop_table('people')
    op.drop_table('pathways')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_events_entity')

    op.drop_table('audit_events')
    op.drop_table('assets')
    # ### end Alembic commands ###
